# Generated by Django 4.2.4 on 2023-08-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0002_empregado_departamentos_empregado_empresa_and_more'),
        ('hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='empregado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='empregados.empregado'),
        ),
    ]
