# Generated by Django 4.2.4 on 2023-08-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0003_alter_empregado_user'),
        ('documentos', '0002_documento_proprietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='proprietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empregados.empregado'),
            preserve_default=False,
        ),
    ]
