# Generated by Django 4.2.4 on 2023-08-26 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empregados', '0002_empregado_departamentos_empregado_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
